wip

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,19 +2,40 @@
 
 set -o pipefail
 
+#build_image() {
+#    local OS_IMAGE="$1"
+#    local PHP_VERSION="$2"
+#    local DOCKER_TAG="$3"
+#
+#    printf "Building Base Docker image ($OS_IMAGE)...\n"
+#    if ! docker build --build-arg OS_IMAGE="$OS_IMAGE" --build-arg PHP_VERSION="$PHP_VERSION" -f Dockerfile -t "humaid/larahost:$DOCKER_TAG" .; then
+#        printf "Error building base Docker image\n" >&2
+#        return 1
+#    fi
+#}
+#build_image2() {
+#    local OS_IMAGE="$1"
+#    local PHP_VERSION="$2"
+#    local DOCKER_TAG="$3"
+#
+#    if ! docker build --build-arg OS_IMAGE="$OS_IMAGE" --build-arg PHP_VERSION="$PHP_VERSION" -f Dockerfile-mssql -t "humaid/larahost:$DOCKER_TAG-mssql" .; then
+#        printf "Error building base Docker image\n" >&2
+#        return 1
+#    fi
+#}
+
 build_image() {
     local OS_IMAGE="$1"
-    local PHP_VERSION="$2"
-    local DOCKER_TAG="$3"
-
-    printf "Building Base Docker image ($OS_IMAGE)...\n"
-    if ! docker build --build-arg OS_IMAGE="$OS_IMAGE" --build-arg PHP_VERSION="$PHP_VERSION" -f Dockerfile -t "humaid/larahost:$DOCKER_TAG" .; then
+    local DOCKER_FILE="$2"
+    local PHP_VERSION="$3"
+    local DOCKER_TAG="$4"
+    if ! docker build --build-arg OS_IMAGE="${OS_IMAGE}" --build-arg PHP_VERSION="${PHP_VERSION}" -f "${DOCKER_FILE}" -t "humaid/larahost:${DOCKER_TAG}" .; then
         printf "Error building base Docker image\n" >&2
         return 1
     fi
 }
 
 
-build_image "alpine:3.19" "81" "8.1"
-build_image "alpine:3.20" "82" "8.2"
-build_image "alpine:3.20" "83" "8.3"
+
+build_image "alpine:3.20" "Dockerfile" "82" "8.2"
+build_image "humaid/larahost:8.2" "Dockerfile-mssql" "82" "8.2-mssql"
