wip

diff --git a/build b/build
--- a/build
+++ b/build
@@ -25,19 +25,17 @@ set -o pipefail
 #}
 
 build_image() {
-    local OS_IMAGE="$1"
-    local DOCKER_FILE="$2"
-    local PHP_VERSION="$3"
-    if ! docker build --build-arg OS_IMAGE="${OS_IMAGE}" --build-arg PHP_VERSION="${PHP_VERSION}" -f "${DOCKER_FILE}" -t "humaid/larahost:${PHP_VERSION}" .; then
-        printf "Error building base Docker image\n" >&2
-        return 1
-    fi
+  local OS_IMAGE="$1"
+  local DOCKER_FILE="$2"
+  local PHP_VERSION="$3"
+  if ! docker build --build-arg OS_IMAGE="${OS_IMAGE}" --build-arg PHP_VERSION="${PHP_VERSION}" -f "${DOCKER_FILE}" -t "humaid/larahost:${PHP_VERSION}" .; then
+    printf "Error building base Docker image\n" >&2
+    return 1
+  fi
 }
 
-
-
-#build_image "ubuntu:24.04" "Dockerfile" "8.0"
-#build_image "ubuntu:24.04" "Dockerfile" "8.1"
-#build_image "ubuntu:24.04" "Dockerfile" "8.2"
-#build_image "ubuntu:24.04" "Dockerfile" "8.3"
+build_image "ubuntu:24.04" "Dockerfile" "8.0"
+build_image "ubuntu:24.04" "Dockerfile" "8.1"
+build_image "ubuntu:24.04" "Dockerfile" "8.2"
+build_image "ubuntu:24.04" "Dockerfile" "8.3"
 build_image "ubuntu:24.04" "Dockerfile" "8.4"
